name: Cricket Auction CI

on:
  push:
    branches:
      - main

jobs:
  run-js:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Run Cricket Auction Project
        run: node app.js